# Generated by Django 3.0.4 on 2020-03-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(max_length=100)),
                ('area_code', models.CharField(max_length=200)),
                ('number', models.IntegerField(max_length=100)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.contact')),
            ],
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.contact')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.contact')),
            ],
        ),
    ]
