# Generated by Django 3.0.4 on 2020-03-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(),
        ),
    ]
